### ISSUE TITLE
Axis config domain not functioning

### ISSUE THREAD

**Issue by skokenes** [vega/vega-lite#2328]
According to API docs, "To provide themes for all axes, the axis config config: {axis: {...}} can contain the following properties:"

And then lists properties for domain such as `domain`, `domainColor`, `domainWidth`.

None of these appear to be working however. Instead, the `tick` styles are also styling the domain. For example, this spec:
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
      {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"}
  },
  "config": {
    "axis": {
      "labelFontSize": 16,
      "domainColor": "green",
      "tickColor": "red",
      "tickWidth": 3
    }
  }
}
```

Produces this chart:
![screen shot 2017-04-30 at 11 13 48 am](https://cloud.githubusercontent.com/assets/5554373/25565534/83024240-2d96-11e7-9215-f28bef978118.png)

**Comment by skokenes** [comment]
This looks like it was resolved by #2329

**Comment by skokenes** [comment]
Actually, after further review...

`domain: true/false` works
`domainColor: "red"` does not work
`domainWidth: 3` does not work

It appears that domain color and width are still being controlled by `tickColor` and `tickWidth`. Try this schema in editor
```{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
      {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"}
  },
  "config": {
    "axis": {
      "domain": true,
      "domainColor": "red",
      "domainWidth": 6,
      "tickColor": "cyan",
      "tickWidth": 2
    }
  }
}
```

**Comment by g3o2** [comment]
__Test results with the following dependencies__: vega 3.0.0-beta.30, vega-lite 2.0.0-beta.2, vega-embed 3.0.0-beta.14

* `domain` works as expected and overrides `domainColor`. Intriguing though that it also overrides `domainWidth` when the latter is set to `0`;
* `domainColor` still does not react at all, same as `domainWidth`;
* `tickColor` works as expected only when `domain` is set to `false`. When the latter is set to `true`, `tickColor` also sets the color of the axis baseline, which it should not;
* `tickWidth` interacts exactly the same way with `domain` than `tickColor`, i.e. not as expected;
```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "grouped lines",
  "width": 300,
  "data": {
    "values": [
      {"year": 2012, "cat" : "orig", "val": 90}, {"year": 2012, "cat" : "adj", "val": 110},
      {"year": 2013, "cat" : "orig", "val": 70}, {"year": 2013, "cat" : "adj", "val": 100},
      {"year": 2014, "cat" : "orig", "val": 130}, {"year": 2014, "cat" : "adj", "val": 105},
      {"year": 2015, "cat" : "orig", "val": 180}, {"year": 2015, "cat" : "adj", "val": 120}
    ]
  },
  "mark": "line",
  "encoding": {
    "x": {
      "field": "year", "type": "temporal", "timeUnit": "year",
      "axis": { "title": "", "labelAngle": 0 }
    },
    "y": { "field": "val", "type": "quantitative" },
    "color": { "field": "cat", "legend": null }
  },
  "config": {
    "axis": { 
      "domain": true,
      "domainColor": "lightgray"
    }
  }
}
```

**Comment by kanitw** [comment]
@NeelMohapatra  Can you help test these?  It seems like if these are bugs, they are bugs in Vega.

**Comment by NeelMohapatra** [comment]
I think you're right. Seems to be a vega issue.
Follow up here https://github.com/vega/vega/issues/815
